---
name: "taiko"

services:
  app:
    build:
      context: "./"
      dockerfile: "./Dockerfile.dev"
      args:
        - "ELIXIR_VERSION=1.16.0-slim"
        - "USER_ID=${USER_ID:-1000}"
    working_dir: "/app"
    command: "mix phx.server"
    restart: "unless-stopped"
    user: "dev"
    tty: true
    stdin_open: true
    volumes:
      - type: "bind"
        source: "./"
        target: "/app"
        read_only: false
    ports:
      - "4000:4000"
    # depends_on:
    #   db:
    #     condition: service_healthy

  db:
    image: "postgres:15.5"
    restart: "unless-stopped"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=taiko_dev"
    volumes:
      - type: "volume"
        source: "pg_data"
        target: "/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD", "pg_isready", "--quiet", "--dbname", "taiko_dev", "--username", "postgres"]
      timeout: "45s"
      interval: "10s"
      retries: 10

volumes:
  pg_data:
    driver: "local"
...
